---
AlignParameters:
  Enabled: false

Encoding:
  Enabled: false

ClassLength:
  Enabled: false

MethodLength:
  Enabled: false

LineLength:
  Enabled: false

Documentation:
  Enabled: false

PerceivedComplexity:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

Style/FileName:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

AllCops:
  UseCache: false
  Exclude:
    - 'Guardfile'
    - 'test/**/*_test.rb'
    - 'test/**/*_spec.rb'
    - 'bin/**'
    - 'cookbooks/**/*'

Style/GuardClause:
  Enabled: false
